### PR TITLE
correct authenticationmode description syntax error

### PR DESCRIPTION
**Pull request by sanshengshui**
origin:

```java
/**
 * List of authentication modes (ordered by preference).
 */
@Option(names = { "-a",
"--auth" }, split = ":", description = "use authentikation modes. '--help-auth' to list available authentication modes.")
public List<AuthenticationMode> authenticationModes;
```

Syntax error exists

### CODE REVIEW

**Comment by boaks** [comment]
Thanks for spotting and fixing the typo.

In order to merge your PR, you would need to follow the [contribution guide](./CONTRIBUTING.md).
In short, you need to fill a ECA for the e-mail address used in the commit.

In the case you feel, that filling that ECA is little overdone for fixing a "typo", I may fix it under my own name. The "authorship" of an simple typo fix may not be that relevant.

**Comment by sanshengshui** [comment]
In order to contribute to this project later, I will finish it [contribution guide](https://github.com/eclipse-californium/californium/blob/main/CONTRIBUTING.md).

**Comment by sanshengshui** [comment]
fix it under my your name, filling that ECA and create eclipse account  takes some time

**Comment by boaks** [comment]
Done.
Again thanks for reporting.

**Pull request closed without merging**
