### PR TITLE
fix: account for removal of disallowed characters in ipv6 scopes

### PR DESCRIPTION
**Pull request by hasheddan**
Updates the StringUtil tests to account for the removal of disallowed characters in ipv6 scopes. Previously tests would fail if one of these characters was present.

### CODE REVIEW

**Comment by boaks** [comment]
Thanks for the PR!
If you like, please sign an [ECA](http://www.eclipse.org/legal/ECA.php).
If you don't like, I convert this into an issue and implement a fix on my own ;-).

**Review by hasheddan — COMMENTED** [review]
Hmm I created an account and signed ECA -- not sure why still failing 🤔

**Comment by boaks** [comment]
On a first try, it may be an error in the eclipse verification stuff.
I will need a moment to analyze an try to sort it out.

**Comment by hasheddan** [comment]
@boaks thanks! Let me know if you need me to update anything :)

**Comment by boaks** [comment]
My result:

You have a valid ECA with the e-mail address of the commit.

Sometimes the Eclipse Validation takes some time. I already tried it twice. I will retry it tomorrow before I start the release. If that still fails, I will check it again, document it and merge it before the release.

**Comment by boaks** [comment]
LGTM

done :-)

**Pull request merged**
