### PR TITLE
Adapt ObserveRelation to keep provided observe options.

### PR DESCRIPTION
**Pull request by boaks**

### CODE REVIEW

**Comment by ashvayka** [comment]
From the first look, this is exactly what we need. But I will confirm once we do additional tests. Thank you so much!

**Comment by boaks** [comment]
Your welcome.

**Comment by ashvayka** [comment]
Hi @boaks, Thank you for the proposed changes. I confirm that those changes will help us implement our case.

**Comment by boaks** [comment]
Does it require a minor release, 3.11 for you?

Usually I need to start and pass a "progress review" (once a year) in order to do new releases. So I guess, it will take at least 2 weeks.

**Comment by ashvayka** [comment]
We plan to release ThingsBoard 3.7 within the next 3-4 months. So there is no rush, but we just need to know which version of the Californium we should use and when to expect it.

**Pull request merged**
