### PR TITLE
Update web-site.

### PR DESCRIPTION
**Pull request by boaks**
Signed-off-by: Achim Kraus <achim.kraus@cloudcoap.net>

### CODE REVIEW

**Comment by sophokles73** [comment]
IMHO we should not change the base URL until a conclusion has been reached in https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1991

**Comment by boaks** [comment]
OK, I wasn't aware, that this is in discussion. 
So, wait for the outcome. 
The old github link will be forwarded, so that's also not that urgent.

**Comment by boaks** [comment]
I removed the adaption of the web-site URL, if that comes, I will add it again.
So it's only the update to the new github repo.

**Review by sophokles73 — APPROVED** [review]
LGTM

**Pull request merged**
